name: Backend Deploy

on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/27981201718/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider'
        service_account: 'github-actions@mergex-382319.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v1'
      with:
        name: 'mergex-backend'
        runtime: 'python39'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}/healthz"'