openapi: 3.0.0
info:
  title: Emotion Detection API
  description: A Flask API for detecting emotion in response to a given question and biography
  version: '1.0'
servers:
  - url: http://localhost:5000/
paths:
  /:
    post:
      summary: Predict emotion and generate an answer
      requestBody:
        description: The biography and question for which to predict the emotion and generate an answer
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bio:
                  type: string
                  description: The biography to use in the prediction
                question:
                  type: string
                  description: The question to use in the prediction
              required:
                - bio
                - question
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  emotion:
                    type: string
                    description: The predicted emotion
                  answer:
                    type: string
                    description: The generated answer
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  emotion:
                    type: string
                    description: The error emotion
                  answer:
                    type: string
                    description: The error message
